import Foundation
import ProjectDescription

let workspace = Workspace(
    name: "ExchangesApp",
    projects: [
        "./Projects/App",
        "./Projects/DependencyInjection",
        "./Projects/DesignSystem",
        "./Projects/Home",
        "./Projects/Detail"
    ],
    schemes: [],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
