import Foundation
import ProjectDescription

let workspace = Workspace(
    name: "ExchangesApp",
    projects: [
        "./Projects/App",
    ],
    schemes: [],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
