name: Pull request workflow

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  paths-filter:
    name: Verify targets to run tests
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app:
              - 'Projects/App/**'
      - name: Generate matrix
        id: matrix
        run: |
          targets=()
          if [ "${{ steps.filter.outputs.app }}" == "true" ]; then
            targets+=("App")
          fi
          
          if [ ${#targets[@]} -gt 0 ]; then
            matrix="{\"target\": [$(printf '"%s",' "${targets[@]}" | sed 's/,$//')]}"
          else
            matrix='{"target": []}'
          fi
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
  
  test:
    name: Test ${{ matrix.target }}
    runs-on: macos-26
    needs: paths-filter
    if: fromJson(needs.paths-filter.outputs.matrix).target[0] != null
    strategy:
      matrix: ${{ fromJson(needs.paths-filter.outputs.matrix) }}
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: CI Setup
        run: make ci-setup
      - name: Install dependencies
        run: tuist install
      - name: Generate project
        run: tuist generate --no-open
      - name: Run tests for ${{ matrix.target }}
        run: exec fastlane tests target:${{ matrix.target }}
      - name: Check code coverage
        run: fastlane tests_coverage target:${{ matrix.target }}
      # - name: Zip reports
      #   run: zip -r reports.zip reports/
      # - name: Upload test reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-reports-${{ matrix.target }}
      #     path: reports.zip

  # coverage:
  #   name: Code Coverage ${{ matrix.target }}
  #   runs-on: ubuntu-latest
  #   needs: [paths-filter, test]
  #   if: fromJson(needs.paths-filter.outputs.matrix).target[0] != null
  #   strategy:
  #     matrix: ${{ fromJson(needs.paths-filter.outputs.matrix) }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4.1.1
  #     - name: Install Slather
  #       run: gem install slather
  #     - name: Download test reports
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: test-reports-${{ matrix.target }}
  #         path: .
  #     - name: Unzip reports
  #       run: unzip reports.zip
  #     - name: Check code coverage
  #       run: fastlane tests_coverage target:${{ matrix.target }}

  check-project:
    name: Check project generation
    runs-on: macos-26
    needs: paths-filter
    if: fromJson(needs.paths-filter.outputs.matrix).target[0] == null
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: CI Setup
        run: make ci-setup
      - name: Install dependencies
        run: tuist install
      - name: Check project generation
        run: tuist generate --no-open