name: Pull request workflow

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:  
  test:
    name: Setup project
    runs-on: macos-26
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: CI Setup
        run: make ci-setup
      - name: Install dependencies
        run: tuist install
      - name: Generate project
        run: tuist generate